### ISSUE TITLE
个人阅读时觉得需要增加更多讲解的部分

### ISSUE THREAD

**Issue by SyMind** [suica/write-you-a-typescript#19]
# 描写类型系统的工具

> 定义：若集合 R 满足 R⊆S×S，那么 R 就是一种集合 S 上的二元关系(Binary Relation)。

对于一个毕业多年的人来说，已经需要搜索才能知道 集合 R⊆S×S 表示关系 R 是集合 S 的笛卡尔积 S×S 的子集，这里可能需要多增加一些解释 ಥ_ಥ。

# 俯瞰编程语言：宇宙的层级

> 函数的定义域(Domain)、陪域(Codomain)

需要对这两个术语增加解释。

> 二阶类型(Kind)宇宙

看完之后只有迷惑，对其定义和用处均无法得到了解。

**Comment by suica** [comment]
非常感谢你的建议！
1. 对于首次出现的符号和概念，将增加解释以及例子，争取做到自包含。整体的行文风格也会作调整，减轻生硬的学术味道。
2. "俯瞰编程语言：宇宙的层级" 一节会从第一章移动到最后一章，用来扩展读者的视野。[Kind](https://en.wikipedia.org/wiki/Kind_(type_theory))不会在这个教程内涉及，因此将删去。就算之后涉及到，也会另外新开章节处理。

**Comment by suica** [comment]
已经修复。如果还有问题可以随时repo
