### ISSUE TITLE
类型检查器 - n元关系举例 符号错误

### ISSUE THREAD

**Issue by jeane-zz** [suica/write-you-a-typescript#32]
如题，类型检查器 - n元关系举例 符号错误。

访问链接： https://suica.github.io/write-you-a-typescript/docs/tutorial-chapter-2/tools-to-describe-type-systems#n%E5%85%83%E5%85%B3%E7%B3%BB

见下图
![11](https://github.com/suica/write-you-a-typescript/assets/21193997/3850b54b-4450-43cc-bd97-44c5569716f4)

**Comment by suica** [comment]
非常感谢！已修复。
